version: 0.2

batch:
  fast-fail: false
  build-graph:
    - identifier: build1
      env:
        fleet: test-fleet
    - identifier: build2
      buildspec: build2.yml
      env:
        fleet: test-fleet
      depend-on:
        - build1

phases:
  build:
    on-failure: continue
    commands:
      - mkdir -p Data
      - touch Data/test.txt
      - echo "test content" >> Data/test.txt
      - system_profiler SPHardwareDataType | grep "Hardware UUID"

cache:
  paths:
    - 'Data/**/*'
