version: 0.2

batch:
  fast-fail: false
  build-graph:
    - identifier: build1
      env:
        fleet: mac
    - identifier: build2
      buildspec: build2.yml
      env:
        fleet: mac
      depend-on:
        - build1

phases:
  build:
    on-failure: continue
    commands:
      - mkdir -p Data
      - sudo chmod -R 777 Data
      - touch Data/test.txt
      - echo "test content" >> Data/test.txt
      - system_profiler SPHardwareDataType | grep "Hardware UUID" || true
      - uname -s || true
      - echo $OSTYPE || true

cache:
  paths:
    - 'Data/**/*'
