name: Cache restore workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  cache:
    name: Cache
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Restore cache
      - uses: actions/cache/restore@v4
        id: cache-restore
        with:
          path: node_modules/
          key: ${{ runner.os }}-test-files-${{ github.sha }}

      - name: Test cache
        run: |
          npm install
          date +%T
          /usr/bin/tar --posix -cf cache.tzst --exclude cache.tzst -P node_modules/ --use-compress-program zstdmt
          date +%T
          /usr/bin/tar --use-compress-program=unzstd -xf cache.tzst
          ls node_modules/
          date +%T



      # Save cache
      - uses: actions/cache/save@v4
        id: cache-save
        with:
          path: node_modules/
          key: ${{ runner.os }}-test-files-${{ github.sha }}