name: Cache restore workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  cache:
    name: Cache
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Restore cache
      - uses: actions/cache/restore@v4
        id: cache-restore
        with:
          path: test_files
          key: ${{ runner.os }}-test-files-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-test-files-

      # Verify cache contents
      - name: Check cache contents
        run: |
          echo "Number of files in test_files:"
          ls test_files | wc -l

      # Save cache
      - uses: actions/cache/save@v4
        id: cache-save
        with:
          path: test_files
          key: ${{ runner.os }}-test-files-${{ github.sha }}